### ISSUE TITLE
Private Key should be a buffer issues

### ISSUE THREAD

**Issue by lowkaweiken** [imperialsoftech/coffee-supplychain-ethereum#4]
Hello, I have followed the updated README file, and still faced this issue. Below is the error from the Bash CLI:

`$ truffle migrate --network rinkeby reset
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Deploying Migrations...

C:\Users\KEN LOW\Desktop\Coffee Dapp\coffee-supplychain-ethereum\node_modules\ethereumjs-util\dist\index.js:369
  **var sig = secp256k1.sign(msgHash, privateKey);
                      ^**
TypeError: private key should be a Buffer
    at Object.exports.ecsign (C:\Users\KEN LOW\Desktop\Coffee Dapp\coffee-supplychain-ethereum\node_modules\ethereumjs-util\dist\index.js:369:23)
`

**Comment by lowkaweiken** [comment]
Found the solution:

Make sure the from address (in truffle.js) you use when sending transactions is entirely lowercase or you will see an error like this:

`TypeError: private key should be a Buffer`

**Comment by imperialsoftech** [comment]
> Found the solution:
> 
> Make sure the from address (in truffle.js) you use when sending transactions is entirely lowercase or you will see an error like this:
> 
> `TypeError: private key should be a Buffer`

@lowkaweiken thanks

**Comment by cristiano-c** [comment]
Using lowercase doesn't work for me.
